In [1]:
from implementations import *

In [2]:
data_path = 'data/train.csv'
data_label, data_origin, _ = load_csv_data(data_path, sub_sample=False)
data_origin

array([[ 138.47 ,   51.655,   97.827, ...,    1.24 ,   -2.475,  113.497],
       [ 160.937,   68.768,  103.235, ..., -999.   , -999.   ,   46.226],
       [-999.   ,  162.172,  125.953, ..., -999.   , -999.   ,   44.251],
       ...,
       [ 105.457,   60.526,   75.839, ..., -999.   , -999.   ,   41.992],
       [  94.951,   19.362,   68.812, ..., -999.   , -999.   ,    0.   ],
       [-999.   ,   72.756,   70.831, ..., -999.   , -999.   ,    0.   ]])

In [3]:
data_standardized, data_origin_mean ,data_origin_std = standardize(data_origin)
data_standardized

array([[  0.46141372,   0.24776513,   0.36139276, ...,   0.12369563,
          0.11455315,   0.39995606],
       [  3.16021405,   0.55250482,   1.52766908, ..., -29.65752746,
        -29.65752746,  -0.08526906],
       [-26.45649733,   1.98365853,   1.09655998, ..., -26.45649733,
        -26.45649733,  -0.90453686],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]])

In [4]:
data_label

array([ 1., -1., -1., ...,  1., -1., -1.])

In [5]:
w_initial = np.array([0]*data_standardized.shape[1])
max_iters = 100
gamma = 0.7
gradient_losses, gradient_ws = gradient_descent(data_label, data_standardized, w_initial, max_iters, gamma)

Gradient Descent(0/99): loss=1.0, w0=0.009318153994566869, w1=-0.0007455297303470465
Gradient Descent(1/99): loss=1.001521834661756, w0=-0.44028494457865924, w1=0.05979904645023791
Gradient Descent(2/99): loss=1.2540412441136204, w0=63.15945740994413, w1=-9.010124791954626
Gradient Descent(3/99): loss=40.93520140847524, w0=-9872.521571509425, w1=1412.5636097567692
Gradient Descent(4/99): loss=6277.334585983553, w0=1551106.8047763654, w1=-221970.3649665808
Gradient Descent(5/99): loss=986405.5899601596, w0=-243771461.4621158, w1=34885135.66921705
Gradient Descent(6/99): loss=155025848.37737897, w0=38311700937.058, w1=-5482633778.678366
Gradient Descent(7/99): loss=24364255517.083767, w0=-6021163757354.643, w1=861664611484.5996
Gradient Descent(8/99): loss=3829148216701.045, w0=946301370313379.8, w1=-135421396434733.77
Gradient Descent(9/99): loss=601798649502329.8, w0=-1.487231243947206e+17, w1=2.1283170268772584e+16
Gradient Descent(10/99): loss=9.458020271027827e+16, w0=2.337370358743

Gradient Descent(92/99): loss=1.1923969007884476e+197, w0=2.9467828275820035e+199, w1=-4.217022801276589e+198
Gradient Descent(93/99): loss=1.8740012241793724e+199, w0=-4.631238661076639e+201, w1=6.62758003376154e+200
Gradient Descent(94/99): loss=2.945227873289195e+201, w0=7.278572188996542e+203, w1=-1.0416072943835537e+203
Gradient Descent(95/99): loss=4.628794855455929e+203, w0=-1.1439188732743477e+206, w1=1.6370164527417347e+205
Gradient Descent(96/99): loss=7.2747314420759135e+205, w0=1.7978119260965336e+208, w1=-2.572776593440729e+207
Gradient Descent(97/99): loss=1.1433152517431062e+208, w0=-2.825486839257492e+210, w1=4.043440973773012e+209
Gradient Descent(98/99): loss=1.796863259182237e+210, w0=4.4406068081609896e+212, w1=-6.354774429334104e+211
Gradient Descent(99/99): loss=2.823995890264288e+212, w0=-6.978970332018141e+214, w1=9.987324733971887e+213


In [6]:
w_initial = np.array([0]*data_standardized.shape[1])
max_iters = 100
gamma = 0.7
batch_size = int(data_standardized.shape[0]*0.1)
gradient_stochastic_losses, gradient_stochastic_ws  = stochastic_gradient_descent(data_label, data_standardized, w_initial, batch_size, max_iters, gamma)

SGD(0/99): loss=1.0109866004025014, w0=0.039129554047094506, w1=-0.003911611855527391
SGD(1/99): loss=1.0078669029308651, w0=-0.0014162817532029082, w1=-0.00758540302645439
SGD(2/99): loss=3.029700223271565, w0=0.9365843856946237, w1=0.33810032054083716
SGD(3/99): loss=573.0891868859952, w0=1368.7460494208303, w1=-178.52671035243654
SGD(4/99): loss=257632.79448900843, w0=100456.98195170342, w1=41099.60995691036
SGD(5/99): loss=21879330.61875585, w0=-9134061.594259407, w1=-2592091.2901169085
SGD(6/99): loss=1853564227.026352, w0=761370686.3262926, w1=223437080.2143623
SGD(7/99): loss=673396479.9461037, w0=2186573079.931691, w1=263691391.34726855
SGD(8/99): loss=129586321530.7064, w0=-466582697254.6773, w1=51606998622.96219
SGD(9/99): loss=22472368489022.008, w0=39104324377330.48, w1=-5153554187914.212
SGD(10/99): loss=16851596311330.396, w0=-29397102094357.367, w1=-11471323405876.348
SGD(11/99): loss=3179148440140987.0, w0=-1.150687888613272e+16, w1=1244813499082501.2
SGD(12/99): loss=1

SGD(92/99): loss=1.507377038440406e+115, w0=7.370517316240791e+114, w1=2.905388744811981e+114
SGD(93/99): loss=5.621791020068657e+117, w0=9.423539078751702e+117, w1=-1.6805454734221958e+117
SGD(94/99): loss=5.480935096271205e+117, w0=9.37878874783026e+117, w1=-1.7580863504390987e+117
SGD(95/99): loss=5.47805180695649e+117, w0=9.392812052257977e+117, w1=-1.745967300116758e+117
SGD(96/99): loss=5.47805180695649e+117, w0=9.392812052257977e+117, w1=-1.745967300116758e+117
SGD(97/99): loss=9.312703520954589e+119, w0=4.6037437084192145e+119, w1=1.7771385317217755e+119
SGD(98/99): loss=1.6305677013428776e+122, w0=-7.866713408254515e+121, w1=-3.1358353360347573e+121
SGD(99/99): loss=3.199422417327611e+124, w0=-1.1580360014909633e+125, w1=1.26446264326181e+124


In [7]:
ridge_regression(data_label, data_standardized)

lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.000, Training RMSE=1.000
lambda=0.001, 

In [8]:
least_squares_regression(data_label, data_standardized)

rmse=0.999940049545477


In [9]:
max_iters = 10000
threshold = 1e-8
gamma = 0.01
w_initial = np.array([0]*data_standardized.shape[1], dtype='float64')
logistic_regression_gradient_descent(data_label, data_standardized, w_initial, max_iters, gamma, threshold)

Current iteration=0, loss=173286.79513948376


In [11]:
max_iters = 100
threshold = 1e-8
gamma = 0.01
lambda_ = 0.1
w_initial = np.array([0]*data_standardized.shape[1], dtype='float64')
regularized_logistic_regression(data_label, data_standardized, lambda_, w_initial, max_iters, gamma, threshold)

Current iteration=<built-in function iter>, loss=173286.79513948376
Current iteration=<built-in function iter>, loss=176202.51664451216
Current iteration=<built-in function iter>, loss=179316.1545544692
Current iteration=<built-in function iter>, loss=183546.32960363786
Current iteration=<built-in function iter>, loss=188886.32215113725
Current iteration=<built-in function iter>, loss=195329.44392368844
Current iteration=<built-in function iter>, loss=202869.03788123754
Current iteration=<built-in function iter>, loss=211498.4780831341
Current iteration=<built-in function iter>, loss=221211.16955486214
Current iteration=<built-in function iter>, loss=232000.5481553216
Current iteration=<built-in function iter>, loss=243860.08044465838
Current iteration=<built-in function iter>, loss=256783.26355264022
Current iteration=<built-in function iter>, loss=270763.62504757644
Current iteration=<built-in function iter>, loss=285794.7228057795
Current iteration=<built-in function iter>, loss=301

In [ ]:
# 验证
aI = 2 * data_standardized.shape[0] * 10* np.identity(data_standardized.shape[1])
a = (data_standardized.T.dot(data_standardized) + aI)

w_test.dot(a)

np.identity(data_standardized.shape[1]).dot(data_standardized.T.dot(data_label))

np.identity(data_standardized.shape[1]).shape

np.identity(data_standardized.shape[1]).dot(data_standardized.T.dot(data_label)).shape

data_standardized.shape